# Generated by Django 5.2.3 on 2025-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestreport',
            name='calmar_ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
